spring.application.name=HMS_Demo
#adding database connection url string

spring.datasource.url = jdbc:postgresql://localhost:5432/hospitaldb?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#using the hospitalDB in the sql