spring.application.name=LearningRestApis

#database related start
spring.datasource.url=jdbc:postgresql://localhost:5432/studentsDB

spring.datasource.username = postgres

spring.datasource.password = root

#spring.jpa.hibernate.ddl-auto=create-drop #make database new each time
#make the database once and update each and every time
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql = true
#show the query inside the logs

spring.jpa.properties.hibernate.format_sql=true
#show the query inside logs with human-readable format
#database related end
